### ISSUE TITLE
Update the Projects API to have more granular querying

### ISSUE THREAD

**Issue by aditya-sudarshan** [aditya-sudarshan/jr_design_JIB356#40]

**Comment by saketshirsath** [comment]
As a follow up, I need to add CRUD for degrees bc I forgot initially.

**Comment by aditya-sudarshan** [comment]
Created a querying process for all Student profiles - need to replicate for Projects but that will be quick. Filtering is now enabled on backend and will return the important information about a student profile/project.

**Comment by aditya-sudarshan** [comment]
Implemented the filtering method for projects, need to test
